---
# tasks file for apache
- name: installing apache
  apt: name=apache2 state=present
- name: starting the service
  service: name=apache2 state=started
- name: copying the file
  template: src=index.html.j2  dest=/var/www/html/index.html
  notify: restart apache
